### PR TITLE
Latin Segmenter split camelCased words

### LINKED ISSUE #129: Latin script: Segmenter should split camelCased words
Today, Meilisearch is splitting `snake_case`, `SCREAMING_CASE` and `kebab-case` properly but doesn't split `PascalCase` nor `camelCase`.

### drawback
 Meilisearch doesn't completely support code documentation.

### enhancement
Make Latin Segmenter split camelCased/PascalCase words:
- `"camelCase"` -> `["camel", "Case"]`
- `"PascalCase"` -> `["Pascal", "Case"]`
- `"IJsland"` -> `["IJsland"]` (Language trap)
- `"CASE"` -> `["CASE"]` (another trap)

#### Files expected to be modified
- [/src/segmenter/latin.rs](https://github.com/meilisearch/charabia/blob/dac6b422e43b666cc232430533e61a50abdd3341/src/segmenter/latin.rs)

> Hey! 👋 
Before starting any implementation, make sure that you read the [CONTRIBUTING.md](https://github.com/meilisearch/charabia/blob/main/CONTRIBUTING.md#contributing) file.
In addition to the recurrent rules, you can find some guides to easily implement a `Segmenter` or a `Normalizer`.
Thanks a lot for your Contribution! 🤝

### PR DESCRIPTION
**Pull request by rashmibharambe**
# Pull Request

## Related issue
Fixes #129 

## What does this PR do?
- 
Latin Segmenter - to split camelCased words

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by ManyTheFish** [comment]
Hello @rashmibharambe, could you modify the tests to ensure that your changes are working?
Thanks!

**Comment by rashmibharambe** [comment]
> Hello @rashmibharambe, could you modify the tests to ensure that your changes are working? Thanks!

Tests modified, waiting for build...

**Comment by ManyTheFish** [comment]
Perfect!
I let bors run all the tests, and if everything goes well, your PR will be automatically merged.
Thank you for your contribution!

bors merge

**Comment by rashmibharambe** [comment]
@ManyTheFish - can you help here,

**Comment by ManyTheFish** [comment]
Hey @rashmibharambe, 
first, ensure that the command `cargo test` is working before submitting something on this PR.
Then, a Segmenter is not allowed to allocate a new String, and `replace_all` returns a `Cow<str>` which can allocate a new string. I would suggest using something else to do the job.

**Comment by ManyTheFish** [comment]
Closing due to the loss of activity on this PR letting another contributor fix this issue.
Feel free to reopen this PR when:
- the code compiles
- the tests pass

**Pull request closed without merging**
