### PR TITLE
fix: fixed `chinese-normalization-pinyin` feature test failed

### LINKED ISSUE #290: The `chinese-normalization-pinyin` feature flag doesn't compile
## Reproduction

`cargo test --verbose --features chinese-normalization-pinyin`

## Fix

1) Fix the [CI testing the flag](https://github.com/meilisearch/charabia/blob/eb3326d5de494f9cc497c9903520449e7f43033f/.github/workflows/rust.yml#L30) using `cargo test --verbose --features chinese-normalization-pinyin` instead of `cargo test --verbose --features chinese chinese-normalization-pinyin`
1) the CI should not work anymore
1) Fix the compilation issue [in the normalizer](https://github.com/meilisearch/charabia/blob/main/charabia/src/normalizer/chinese.rs)

related to https://github.com/meilisearch/meilisearch/issues/4629

### PR DESCRIPTION
**Pull request by tkhshtsh0917**
# Pull Request

## Related issue
Fixes #290

## What does this PR do?
- Fixed an issue where build & test would fail with the `chinese-normalization-pinyin` feature flag enabled.
- Fixed CI test command for `chinese-normalization-pinyin` feature. (to prevent recurrence)

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by curquiza** [comment]
looks like there is an issue with bors, trying again

bors merge

**Comment by curquiza** [comment]
Merging by hand since it does not work

**Review by curquiza — APPROVED** [review]
bors merge

**Comment by tkhshtsh0917** [comment]
@ManyTheFish @curquiza 

Hmm... Something doesn't seem to be working...

Should I consider re-issuing the PR?
Please let me know if there is anything I can do to help! :)

**Comment by curquiza** [comment]
I will merge by hand, issue happens something with bors.
- The branch is up to date
- we have an approval
- tests are green

No issue with merging by hand

**Pull request merged**
