### PR TITLE
Replace jemalloc(ator) with mimalloc, which covers wider platforms

### LINKED ISSUE #314: charabia can't be built in Windows due to jemallocator used only for bench
I want to improve and test charabia in Windows but jemallocator fails to be built.
The platforms supported by jemallocator are [limited](https://github.com/tikv/jemallocator?tab=readme-ov-file#platform-support), so it should be disabled in unsupported platforms.

### PR DESCRIPTION
**Pull request by tats-u**
# Pull Request

## Related issue

Fixes #314

## What does this PR do?
The platforms supported by jemallocator are [limited](https://github.com/tikv/jemallocator?tab=readme-ov-file#platform-support). I use Windows but can't build charabia due to it. It should be disabled in unsupported platforms. It is used only for benchmarks.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by ManyTheFish** [comment]
Hello @tats-u, sorry for the delay, can you use mimalloc instead? as you suggested in the issue?

**Comment by tats-u** [comment]
@ManyTheFish It works on Windows MSVC.
`cargo bench` can be run with it in Windows. (I haven't checked its effect)

**Comment by tats-u** [comment]
Can I rebase this branch to main and squash my 2 commits into just one?

**Review by ManyTheFish — APPROVED** [review]
Hello @tats-u,

Github is able to rebase this kind of PR, so I did it with the UI,

Sorry for the delay and thank you for your work,

Bors merge

**Pull request merged**
