### PR TITLE
Use cargo workspace

### PR DESCRIPTION
**Pull request by choznerol**
# Pull Request

## Related issue
Fixes https://github.com/meilisearch/product/discussions/582 (part 1)

## What does this PR do?

Convert the codebase structure to [cargo workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html) according to the conclusion in https://github.com/meilisearch/product/discussions/582#discussioncomment-4331356 .

I found the changing related to cargo workspace can accumulate merge conflict pretty easily, so I'm opening this as a standalone PR. The actual work to bring in https://github.com/choznerol/kvariants will be another follow-up PR #171 base on this branch.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @choznerol 
Thanks a lot for your PRs!
There are git conflicts with this PR, could you please remove them before we review it? 😊 
Sorry it's holiday period in France so we might not be as reactive as usual

**Comment by choznerol** [comment]
> Hello @choznerol Thanks a lot for your PRs! There are git conflicts with this PR, could you please remove them before we review it? 😊 Sorry it's holiday period in France so we might not be as reactive as usual

No problem! Rebased and resolved conflict.

**Comment by curquiza** [comment]
Thanks @choznerol I put @irevoire as reviewer, he will try to review as soon as possible, depending on his holiday time and priority 😇

**Review by ManyTheFish — APPROVED** [review]
Looks good to me!
Sorry @choznerol for the time to review!

**Comment by ManyTheFish** [comment]
bors merge

**Pull request merged**
